name: Dependency Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit --json > audit-report.json

      - name: Convert audit report to CSV (with parent libs)
        run: |
          node -e "
          const fs = require('fs');
          const { execSync } = require('child_process');
          const data = JSON.parse(fs.readFileSync('audit-report.json'));
          const rows = [];

          function findParent(lib) {
            try {
              const output = execSync(\`npm ls \${lib} --all --json\`).toString();
              const tree = JSON.parse(output);
              // Helper: recursively search the dependency tree
              function search(node, target, parent=null) {
                if (!node.dependencies) return null;
                for (const [dep, info] of Object.entries(node.dependencies)) {
                  if (dep === target) return parent || 'root';
                  const found = search(info, target, dep);
                  if (found) return found;
                }
                return null;
              }
              return search(tree, lib) || 'unknown';
            } catch (e) {
              return 'unknown';
            }
          }

          if (data.vulnerabilities) {
            for (const [name, vuln] of Object.entries(data.vulnerabilities)) {
              const parent = findParent(name);
              rows.push([
                name,
                parent,
                vuln.severity,
                vuln.via.map(v => typeof v === 'string' ? v : v.title).join('; '),
                vuln.range,
                vuln.fixAvailable ? JSON.stringify(vuln.fixAvailable) : 'No fix'
              ].join(','));
            }
          }

          fs.writeFileSync(
            'vulnerable-report.csv',
            'package,parent,severity,issues,range,fix\n' + rows.join('\n')
          );
          "

      - name: Upload audit report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: dependency-audit
          path: vulnerable-report.csv
