name: Dependency scan and map parents

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: npm-audit
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run npm audit (JSON)
        run: |
          set -e
          # produce npm-audit.json. npm audit may exit non-zero; capture output but still create file.
          npm audit --json > npm-audit.json || true
          # show a small preview
          echo "---- audit preview ----"
          head -n 200 npm-audit.json || true

      - name: Upload audit artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit
          path: npm-audit.json

  map-parents:
    needs: audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Download audit artifact
        uses: actions/download-artifact@v4
        with:
          name: npm-audit
          path: .

      - name: Install dependencies (for npm ls to build tree)
        run: npm ci || npm install

      - name: Add script file
        # No-op if script already in repo; ensure it exists
        run: |
          mkdir -p scripts
          cat > scripts/find-vulnerable-parents.js <<'JS'
          // (You can paste the full script here if it's not in the repo already)
          JS
        shell: bash

      - name: Run mapping script
        run: node scripts/find-vulnerable-parents.js

      - name: Upload CSV report
        uses: actions/upload-artifact@v4
        with:
          name: vulnerable-report
          path: vulnerable-report.csv
