name: Dependency Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit --json > npm-audit.json

      - name: Find vulnerable parents and create CSV
        run: node scripts/find-vulnerable-parents.js

      - name: Upload audit report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-audit
          path: vulnerable-report.csv
